name: Generate code from proto

on:
  pull_request:

jobs:
  gen-from-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install protobuf-compiler
      - name: generate code from proto
        run: make protogen
