name: Generate code from proto

on:
  pull_request:

jobs:
  gen-from-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install protobuf-compiler &&
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.0 &&
          npm install grpc-tools grpc_tools_node_protoc_ts -D &&
          npm install @grpc/grpc-js google-protobuf
      - name: generate code from proto
        run: make protogen
      - name: create pr of generate code
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'run `make protogen`'
          branch: gen-impl-from-${{ steps.latest.outputs.version }}
          delete-branch: true
          title: 'DO NOT EDIT: each language implementation'
