name: npm release
on:
  release:
    types:
    - published
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: cd nodejs
        run: cd ./nodejs
      - run: cat ${{toJSON(github.event.release)}}
      - name: update package.json
        run: |
          cat package.json | (rm package.json;sed -e 's/"version": ".*"/"version": "${{github.event.release.tagName}}"/'>package.json)
      - name: npm install
        run: npm install
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: create pr of generate code
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'npm publish'
          branch: release-npm
          base: 'master'
          body: 'generated by release ${{github.event.release.tagName}}'
          branch-suffix: 'timestamp'
          delete-branch: true
          title: 'Release npm package'

