name: npm release
on:
  push:
    #release:
    #types: [published]
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: cd nodejs
        run: cd ./nodejs
      - name: update package.json
        run: |
          cat package.json | (rm package.json;sed -e 's/"version": ".*"/"version": "0.7.0"/'>package.json)
      - name: npm install
        run: npm install
      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
